version: '3.8'

services:
  telegram_bot:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - AZURE_TRANSLATION_KEY=${AZURE_TRANSLATION_KEY}
      - AZURE_ENDPOINT=${AZURE_ENDPOINT}
      - AZURE_ANALYTICS_KEY=${AZURE_ANALYTICS_KEY}
      - AZURE_ANALYTICS_ENDPOINT=${AZURE_ANALYTICS_ENDPOINT}
    volumes:
      - ./src:/app/src
    restart: unless-stopped
